---
# yaml-language-server: $schema=https://crd.movishell.pl/networking.k8s.io/networkpolicy_v1.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unifi-network-mcp
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: unifi-network
      app.kubernetes.io/name: mcpserver
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              toolhive-basename: unifi-network
      ports:
        - protocol: TCP
          port: 3000
