---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/rabbitmqcluster_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "database"
spec:
  delayStartSeconds: 30
  replicas: 1
  terminationGracePeriodSeconds: 604800
  persistence:
    storage: 2Gi
    storageClassName: dcsi-iscsi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
  secretBackend:
    externalSecret:
      name: rabbitmq-cluster-admin
  service:
    type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-cluster-admin
stringData:
  default_user.conf: |
    default_user = admin
    default_pass = adminpass
  username: admin
  password: adminpass
  host: rabbitmq-cluster.database.svc.cluster.local
  port: "5672"
  provider: rabbitmq
  type: rabbitmq
  connection_string: amqp://admin:adminpass@rabbitmq-cluster.database.svc.cluster.local:5672/
---
apiVersion: v1
kind: Secret
metadata:
  name: integrations-app-user-import
stringData:
  username: integrations-app
  password: integrations-app
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/user_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: integrations-app
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  importCredentialsSecret:
    name: integrations-app-user-import
  tags:
    - management
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/vhost_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: integrations-app
spec:
  name: integrations-app
  rabbitmqClusterReference:
    name: rabbitmq-cluster
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/permission_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: integrations-app
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  vhost: integrations-app
  userReference:
    name: integrations-app
  permissions:
    configure: ".*"
    read: ".*"
    write: ".*"
