---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/rabbitmqcluster_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "database"
spec:
  delayStartSeconds: 30
  replicas: 1
  terminationGracePeriodSeconds: 604800
  persistence:
    storage: 2Gi
    storageClassName: dcsi-iscsi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
  service:
    type: ClusterIP
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                env:
                  - name: RABBITMQ_DEFAULT_USER
                    value: "admin"
                  - name: RABBITMQ_DEFAULT_PASS
                    value: "adminpass"
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/user_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: integrations-app
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/vhost_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: integrations-app
spec:
  name: integrations-app
  rabbitmqClusterReference:
    name: rabbitmq-cluster
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/vhost_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: shared
spec:
  name: shared
  rabbitmqClusterReference:
    name: rabbitmq-cluster
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/permission_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: integrations-app
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  vhost: integrations-app
  user: integrations-app
  permissions:
    configure: ".*"
    read: ".*"
    write: ".*"
---
# yaml-language-server: $schema=https://crd.movishell.pl/rabbitmq.com/permission_v1beta1.json
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: shared
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster
  vhost: shared
  user: integrations-app
  permissions:
    configure: ".*"
    read: ".*"
    write: ".*"
