---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rabbitmq
spec:
  hostnames:
    - mq.${PRIVATE_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: rabbitmq-cluster
          port: 15672
      matches:
        - path:
            type: PathPrefix
            value: /
