---
# Main Doco-CD instance. It is deployed by doco-cd-updater through
# .doco-cd.updater.yaml; the TrueNAS SCALE UI runs the updater instance.

configs:
  poll-config.yml:
    content: |
      - url: https://github.com/ishioni/homelab-ops.git
        reference: master
        interval: 3600

networks:
  apps:
    name: apps

services:
  app:
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    container_name: doco-cd
    environment:
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      GIT_COMMIT_STATUS: "true"
      GIT_SCM_PROVIDER: github
      HTTP_PORT: 8080
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN: ${SECRET_PROVIDER_ACCESS_TOKEN}
      SECRET_PROVIDER_CACHE_ENABLED: "true"
      SECRET_PROVIDER_CACHE_TTL: "6h"
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.109.0@sha256:a985224469c19ff0bbc1e1437b362bc8c915d9a55ec6470858b3f83cc21863b1
    ports:
      - 8080:8080
      - 9120:9120
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
