---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-operator-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
        session-secret: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: renovate-operator
