---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
spec:
  chartRef:
    kind: OCIRepository
    name: onepassword-connect
  interval: 30m
  values:
    connect:
      api:
        imageRepository: ghcr.io/1password/connect-api
        serviceMonitor:
          enabled: true
      credentialsName: onepassword-secret
      sync:
        imageRepository: ghcr.io/1password/connect-sync
