---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/serviceaccount_v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/clusterrolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: actions-runner
    namespace: github
---
# yaml-language-server: $schema=https://crd.movishell.pl/talos.dev/serviceaccount_v1alpha1.json
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: actions-runner
spec:
  roles:
    - os:admin
