---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 30m
  values:
    fullnameOverride: gatus

    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret gatus-secret
      configmap.reloader.stakater.com/reload: &configmap gatus-configmap

    gatus:
      delayStartSeconds: "5"
      env:
        TZ: ${CONFIG_TIMEZONE}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
        PRIVATE_DOMAIN: ${PRIVATE_DOMAIN}
      envFrom:
        - secretRef:
            name: *secret
      logLevel: ""

    sidecar:
      kinds:
        httproute:
          enable: true

    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
        envFrom:
          - secretRef:
              name: *secret

    config:
      existingConfigMap: *configmap
      items:
        - key: config.yaml
          path: config.yaml

    resources:
      requests:
        cpu: 110m
        memory: 100Mi
      limits:
        memory: 314Mi

    monitoring:
      serviceMonitor:
        enabled: true
        interval: 1m
        scrapeTimeout: 10s
        path: /metrics

    httpRoute:
      enabled: true
      hostnames: ["${HOSTNAME}"]
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
