---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 30m
  values:
    fullnameOverride: gatus

    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret gatus-secret
      configmap.reloader.stakater.com/reload: &configmap gatus-configmap

    gatus:
      image:
        repository: ghcr.io/twin/gatus
        tag: v5.36.0
        digest: sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
      port: &port 80
      delayStartSeconds: "5"
      env:
        TZ: ${CONFIG_TIMEZONE}
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
        PRIVATE_DOMAIN: ${PRIVATE_DOMAIN}
      envFrom:
        - secretRef:
            name: *secret
      livenessProbe: &probes
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      readinessProbe: *probes
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: { drop: ["ALL"] }

    sidecar:
      image:
        repository: ghcr.io/home-operations/gatus-sidecar
        tag: 0.3.2
        digest: sha256:c6550b40f444337d953e622b3ad6dd9b28e80a664dfcd59d0f8551997e870b8e
      kinds:
        httproute:
          enable: true
          auto: true
        service:
          enable: true

    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
        envFrom:
          - secretRef:
              name: *secret

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 110m
        memory: 100Mi
      limits:
        memory: 314Mi

    serviceAccount:
      automount: true

    rbac:
      create: true
      type: ClusterRole

    service:
      port: *port

    monitoring:
      serviceMonitor:
        enabled: true
        interval: 1m
        scrapeTimeout: 10s
        path: /metrics

    httpRoute:
      enabled: true
      hostnames: ["${HOSTNAME}"]
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https

    config:
      existingConfigMap: *configmap
      items:
        - key: config.yaml
          path: config.yaml
