---
# This target is used by the bootstrap updater instance to deploy the main
# Doco-CD instance. It deliberately does not deploy the application stacks.
name: doco-cd
reference: master
working_dir: ./docker/.doco-cd
compose_files:
  - docker-compose.app.yaml
external_secrets:
  GIT_ACCESS_TOKEN: op://Homelab/flux/GITHUB_TOKEN
  SECRET_PROVIDER_ACCESS_TOKEN: op://Homelab/op-connect/API/OP_CONNECT_TOKEN
  WEBHOOK_SECRET: op://Homelab/actions-runner-controller/WEBHOOK_SECRET
