---
# yaml-language-server: $schema=https://crd.movishell.pl/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name dexd
spec:
  staticConfigs: [targets: ["leo.${PRIVATE_DOMAIN}:4320"]]
  metricsPath: /metrics
  honorTimestamps: true
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
    - sourceLabels: [__address__]
      regex: '([^:]+):\d+'
      replacement: "$1"
      targetLabel: instance
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanadashboard_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dexd
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  allowCrossNamespaceImport: true
  datasources:
    - datasourceName: prometheus
      inputName: DS_PROMETHEUS
  folder: Operators
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  url: https://raw.githubusercontent.com/ishioni/dexd/refs/tags/0.4.0/deploy/grafana-dashboard.json
