---
# yaml-language-server: $schema=https://crd.movishell.pl/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name rustfs
spec:
  staticConfigs: [targets: ["otel.ishioni.casa"]]
  metricsPath: /metrics
  scheme: HTTPS
  honorTimestamps: true
  honorLabels: true
---
# yaml-language-server: $schema=https://crd.movishell.pl/grafana.integreatly.org/grafanadashboard_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: rustfs
spec:
  allowCrossNamespaceImport: true
  datasources:
    - datasourceName: prometheus
      inputName: DS_PROMETHEUS
  folder: Storage
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  url: https://raw.githubusercontent.com/rustfs/rustfs/refs/heads/main/.docker/observability/grafana/dashboards/rustfs.json
