---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: rcdn-proxy
spec:
  endpoints:
    - fqdn:
        hostname: traefik.${PRIVATE_DOMAIN}
        port: 443
  tls:
    insecureSkipVerify: true
