---
services:
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.159.0@sha256:110f4ad8974faa402ba1700950ddfc0b711ea25ae281a8358b98eb58de082765
    container_name: otel-collector
    restart: unless-stopped
    networks:
      apps:
    expose:
      - &metricsport ${APP_PORT}
      - ${INGEST_PORT}
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.otel-collector.loadbalancer.server.port: *metricsport
      traefik.http.routers.otel-collector.entrypoints: https
      traefik.http.routers.otel-collector.rule: Host(`${HOST}`)
      traefik.http.routers.otel-collector.tls: true
      traefik.http.routers.otel-collector.service: otel-collector
      dexd.enabled: "true"

networks:
  apps:
    external: true
