---
services:
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.154.0@sha256:e9d3163c8150012f06c61a0b4388569c0d2ca9648ac9591d8b5763717f2339e3
    container_name: otel-collector
    restart: unless-stopped
    networks:
      apps:
    expose:
      - &metricsport ${APP_PORT}
      - ${INGEST_PORT}
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.otel-collector.loadbalancer.server.port: *metricsport
      traefik.http.routers.otel-collector.entrypoints: https
      traefik.http.routers.otel-collector.rule: Host(`${HOST}`)
      traefik.http.routers.otel-collector.tls: true
      traefik.http.routers.otel-collector.service: otel-collector
      dexd.enabled: "true"

networks:
  apps:
    external: true
