---
services:
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.157.0@sha256:f119ada1d6dd20bd5c4cd8c3c1b17b7d19b2e6de01c42d1b50dfc567edd24caf
    container_name: otel-collector
    restart: unless-stopped
    networks:
      apps:
    expose:
      - &metricsport ${APP_PORT}
      - ${INGEST_PORT}
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.otel-collector.loadbalancer.server.port: *metricsport
      traefik.http.routers.otel-collector.entrypoints: https
      traefik.http.routers.otel-collector.rule: Host(`${HOST}`)
      traefik.http.routers.otel-collector.tls: true
      traefik.http.routers.otel-collector.service: otel-collector
      dexd.enabled: "true"

networks:
  apps:
    external: true
