---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  chartRef:
    kind: OCIRepository
    name: it-tools
  interval: 30m
  values:
    controllers:
      it-tools:
        strategy: RollingUpdate
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsUser: 1000
        containers:
          app:
            image:
              repository: ghcr.io/sharevb/it-tools
              tag: 2026.7.11@sha256:5d79e8c7fbf39d6473c282b9c4f86ff85c4900ec22ef766ae3c6f0f9ca8dbb37
            env:
              TZ: ${CONFIG_TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    service:
      app:
        controller: it-tools
        ports:
          http:
            port: 8080
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        # annotations:
        #   gethomepage.dev/enabled: "true"
        #   gethomepage.dev/group: Selfhosted
        #   gethomepage.dev/name: IT-Tools
        hostnames: ["${HOSTNAME}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
