---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tofu-op-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        OP_CONNECT_HOST: http://onepassword-connect.security.svc.cluster.local:8080
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
  dataFrom:
    - extract:
        key: op-connect
---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tofu-s3-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        AWS_S3_ENDPOINT: https://rs3.ishioni.casa
        AWS_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"
        access_key: "{{ .S3_ACCESS_KEY }}"
        secret_key: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: tofu-controller
