---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name konflate-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        KONFLATE_TOKEN: "{{ .GITHUB_TOKEN }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .GITHUB_WEBHOOK_TOKEN }}"
        # KONFLATE_PUSH_TOKEN:
  dataFrom:
    - extract:
        key: konflate
