---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 30m
  values:
    config:
      repo: github://ishioni/homelab-ops
    secret:
      existingSecret: konflate-secret
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames: ["${HOSTNAME}"]
