---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github
spec:
  image: ghcr.io/github/github-mcp-server:v1.1.2@sha256:30197479d8036c7811892bc07e06f9a05c9ef3cdd79bc59f256d50647f95788c
  transport: stdio
  groupRef:
    name: mcp-tools
  secrets:
    - name: github-mcp-secret
      key: GITHUB_PERSONAL_ACCESS_TOKEN
