---
# yaml-language-server: $schema=https://crd.movishell.pl/policies.kyverno.io/namespacedimagevalidatingpolicy_v1.json
apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  name: verify-http-debug-signature
spec:
  autogen:
    podControllers:
      controllers: []
  failurePolicy: Fail
  evaluation:
    background:
      enabled: false
  webhookConfiguration:
    timeoutSeconds: 30
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
  matchImageReferences:
    - glob: ghcr.io/ishioni/http-debug:*
    - glob: ghcr.io/ishioni/http-debug@*
  variables:
    - name: keySecret
      expression: >-
        resource.get("v1", "secrets", "cosign-public-key")
  attestors:
    - name: cosign
      cosign:
        key:
          expression: >-
            string(base64.decode(variables.keySecret.data["cosign.pub"]))
        ctlog:
          insecureIgnoreTlog: true
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  validations:
    - expression: >-
        images.containers.map(image,
          verifyImageSignatures(image, [attestors.cosign])
        ).all(result, result > 0)
      message: failed to verify image signature
