---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: context7
spec:
  image: ghcr.io/stacklok/dockyard/npx/context7:2.1.4
  transport: stdio
  proxyPort: 8080
  secrets:
    - name: context7-mcp-secret
      key: CONTEXT7_API_KEY
