---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserverentry_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServerEntry
metadata:
  name: context7
spec:
  groupRef:
    name: mcp-tools
  remoteUrl: https://mcp.context7.com/mcp
  transport: streamable-http
  headerForward:
    addHeadersFromSecret:
      - headerName: CONTEXT7_API_KEY
        valueSecretRef:
          key: CONTEXT7_API_KEY
          name: context7-mcp-secret
