---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-debug
spec:
  chartRef:
    kind: OCIRepository
    name: http-debug
  interval: 30m
  values:
    controllers:
      http-debug:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ishioni/http-debug
              tag: cosign-experiment@sha256:14cc950d792c6a4f04876f3c5438f08f308b1485e9410ea06b2d46fabe63c86a
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: &port 8080
              readiness: *probes
    service:
      app:
        controller: http-debug
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "${HOSTNAME}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - kind: Service
                name: http-debug
                port: *port
