---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-schemas
spec:
  chartRef:
    kind: OCIRepository
    name: kubernetes-schemas
  interval: 30m
  values:
    config:
      cfPagesProject: homelab-schema
    existingSecret:
      name: kubernetes-schemas
    fullnameOverride: "kubernetes-schemas"
    metrics:
      podMonitor:
        enabled: true
    grafana:
      dashboard:
        operator:
          enabled: true
          defaultInstanceSelector:
            enabled: false
          folder: Operators
          instanceSelector:
            matchLabels:
              grafana.internal/instance: grafana
          datasources:
            - datasourceName: prometheus
              inputName: DS_PROMETHEUS
