---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-schemas
spec:
  chartRef:
    kind: OCIRepository
    name: kubernetes-schemas
  interval: 30m
  values:
    controllers:
      kubernetes-schemas:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret kubernetes-schemas
        containers:
          app:
            image:
              repository: ghcr.io/sholdee/crd-schema-publisher
              tag: v2026.0411.051355@sha256:0b7335987a3ee09c668fa84e1432213f91b4afd106133d655773d1b9da8b11c8
            args: [watch]
            env:
              CF_PAGES_PROJECT: homelab-schema
              POD_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              POD_NAMESPACE:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness:
                enabled: true
                custom: true
                path: /healthz
                port: &port 8080
              readiness:
                enabled: true
                custom: true
                path: /readyz
                port: *port
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    persistence:
      output:
        type: emptyDir
    rbac:
      bindings:
        kubernetes-schemas:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: kubernetes-schemas
          subjects:
            - identifier: kubernetes-schemas
        leader-election:
          type: RoleBinding
          roleRef:
            kind: Role
            name: kubernetes-schemas-leader-election
          subjects:
            - identifier: kubernetes-schemas
      roles:
        kubernetes-schemas:
          type: ClusterRole
          rules:
            - apiGroups: [apiextensions.k8s.io]
              resources: [customresourcedefinitions]
              verbs: [get, list, watch]
        leader-election:
          type: Role
          rules:
            - apiGroups: [coordination.k8s.io]
              resources: [leases]
              verbs: [get, create, update]
    serviceAccount:
      kubernetes-schemas: {}
