---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-schemas
spec:
  chartRef:
    kind: OCIRepository
    name: kubernetes-schemas
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: grafana.integreatly.org
              version: v1beta1
              kind: GrafanaDashboard
              name: kubernetes-schemas-dashboard
            patch: |
              - op: replace
                path: /spec/instanceSelector
                value:
                  matchLabels:
                    grafana.internal/instance: grafana
              - op: add
                path: /spec/folder
                value: Operators
  values:
    config:
      cfPagesProject: homelab-schema
    existingSecret:
      name: kubernetes-schemas
    fullnameOverride: "kubernetes-schemas"
    metrics:
      podMonitor:
        enabled: true
    grafana:
      dashboard:
        operator:
          enabled: true
          instanceSelector:
            matchLabels:
              grafana.internal/instance: grafana
          datasources:
            - datasourceName: prometheus
              inputName: DS_PROMETHEUS
