---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator-crds
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/ai/toolhive/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: toolhive-operator-crds
  interval: 30m
  path: ./kubernetes/apps/ai/toolhive/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-config
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  postBuild:
    substitute:
      HOSTNAME: mcp.${PRIVATE_DOMAIN}
      AUTH_HOSTNAME: auth.${PUBLIC_DOMAIN}
  dependsOn:
    - name: toolhive-operator
  interval: 30m
  path: ./kubernetes/apps/ai/toolhive/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-ops
    namespace: flux-system
  targetNamespace: *namespace
