---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana-image-renderer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AUTH_TOKEN: "{{ .AUTH_TOKEN }}"
        GF_RENDERING_CALLBACK_URL: http://127.0.0.1:3000/
        GF_RENDERING_RENDERER_TOKEN: "{{ .AUTH_TOKEN }}"
        GF_RENDERING_SERVER_URL: http://127.0.0.1:8081/render
  dataFrom:
    - extract:
        key: grafana
