---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name meshmonitor-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        DISABLE_ANONYMOUS: "true"
        DISABLE_LOCAL_AUTH: "true"
        DATABASE_URL: |-
          postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.database.svc.cluster.local:5432/meshmonitor
        OIDC_ISSUER: https://${AUTH_HOSTNAME}/application/o/meshmonitor/
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_REDIRECT_URI: https://meshmonitor.example.com/api/auth/oidc/callback

        INIT_POSTGRES_DBNAME: meshmonitor
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: meshmonitor
    - extract:
        key: cloudnative-pg
