---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: playwright
spec:
  image: mcr.microsoft.com/playwright/mcp:v0.0.70
  transport: streamable-http
  mcpPort: 8931
  proxyPort: 8080
  args:
    - "--port"
    - "8931"
    - "--host"
    - "0.0.0.0"
    - "--allowed-hosts"
    - "*"
