---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # App
        EC_SIGNING_KEY: "{{ .EC_SIGNING_KEY}}"
        HMAC_KEY: "{{ .HMAC_KEY }}"
        # OIDC
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: toolhive
