---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcptelemetryconfig_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPTelemetryConfig
metadata:
  name: prometheus
spec:
  prometheus:
    enabled: true
