---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/virtualmcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway
spec:
  authServerConfig:
    issuer: https://${HOSTNAME}
    signingKeySecretRefs:
      - name: toolhive-secret
        key: signing-key
    hmacSecretRefs:
      - name: toolhive-secret
        key: hmac-key
    tokenLifespans:
      accessTokenLifespan: 1h
      refreshTokenLifespan: 168h
      authCodeLifespan: 10m
    upstreamProviders:
      - name: authentik
        type: oidc
        oidcConfig:
          issuerUrl: https://${AUTH_HOSTNAME}
          clientId: b503054f-dc60-4c71-8e60-47d38fdbcdfe
          clientSecretRef:
            name: toolhive-secret
            key: client-secret
          redirectUri: https://${HOSTNAME/oauth/callback
          scopes:
            - openid
            - profile
            - email
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  groupRef:
    name: mcp-tools
  incomingAuth:
    type: oidc
    oidcConfigRef:
      name: authentik
      audience: "toolhive"
    # oidcConfig:
    #   type: inline
    #   resourceUrl: https://mcp.${SECRET_DOMAIN}/mcp
    #   inline:
    #     audience: https://mcp.${SECRET_DOMAIN}/mcp
    #     issuer: https://mcp.${SECRET_DOMAIN}
    #     jwksAllowPrivateIP: true
  outgoingAuth:
    source: discovered
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          env:
            - name: INSECURE_DISABLE_URL_VALIDATION
              value: "true"
