---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-mcp
spec:
  provider:
    kubernetes:
      remoteNamespace: monitor
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: grafana-mcp
