---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/alerts
  - ../../components/namespace
resources:
  - ./context7-mcp/ks.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./github-mcp/ks.yaml
  - ./hass-mcp/ks.yaml
  - ./kubectl-mcp/ks.yaml
  - ./prometheus-mcp/ks.yaml
  - ./searxng-mcp/ks.yaml
  - ./toolhive/ks.yaml
