---
# yaml-language-server: $schema=https://crd.movishell.pl/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  compression:
    compressor: zstd
  mover:
    podSecurityContext:
      runAsUser: ${APP_UID:=568}
      runAsGroup: ${APP_GID:=568}
      fsGroup: ${APP_GID:=568}
  repository:
    kind: ClusterRepository
    name: leo
  retention:
    keepDaily: 7
  sources:
    - pvc:
        name: ${PVC_CLAIM:=${APP}}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=dcsi-iscsi}
