---
services:
  docker-external-dns:
    image: ghcr.io/ishioni/dexd:0.4.0@sha256:e645dab009d373cca6c6ee6814375cac1201755c1dfde5a5843c2c9e29ccf00e
    container_name: dexd
    restart: unless-stopped
    environment:
      # Required
      UNIFI_HOST: ${UNIFI_HOST}
      UNIFI_API_KEY: ${UNIFI_TOKEN}
      DEFAULT_TARGET: ${DEFAULT_TARGET}
      UNIFI_INSECURE_SKIP_VERIFY: false
      TXT_PREFIX: leo.
      METRICS_ADDR: :4320
    ports:
      - "4320:4320"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
