---
services:
  docker-external-dns:
    image: ghcr.io/ishioni/dexd:v0.3.0@sha256:a073b612ab761430e91628bcfb332f1a6b45d448c1a8953091d5e78174c75b4d
    container_name: dexd
    restart: unless-stopped
    environment:
      # Required
      UNIFI_HOST: ${UNIFI_HOST}
      UNIFI_API_KEY: ${UNIFI_TOKEN}
      DEFAULT_TARGET: ${DEFAULT_TARGET}
      UNIFI_INSECURE_SKIP_VERIFY: false
      TXT_PREFIX: leo.
      METRICS_ADDR: :4320
    ports:
      - "4320:4320"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
