---
services:
  docker-external-dns:
    image: ghcr.io/ishioni/dexd:v0.2.0@sha256:9894dacd2c154bbdddd6a93f797598e5301fd27fb7f3d63639be28539aed6710
    container_name: dexd
    restart: unless-stopped
    environment:
      # Required
      UNIFI_HOST: ${UNIFI_HOST}
      UNIFI_API_KEY: ${UNIFI_TOKEN}
      DEFAULT_TARGET: ${DEFAULT_TARGET}
      UNIFI_INSECURE_SKIP_VERIFY: false
      TXT_PREFIX: leo.
      METRICS_ADDR: :4320
    ports:
      - "4320:4320"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
