---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  chartRef:
    kind: OCIRepository
    name: frigate
  interval: 30m
  values:
    controllers:
      frigate:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: frigate-gpu
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.2@sha256:d4351369984d4a9e2a49ac59736f6490856a7ea11f7790040746d21496967010
            env:
              TZ: ${CONFIG_TIMEZONE}
            envFrom:
              - secretRef:
                  name: frigate-secret
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: 5000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                memory: 8Gi
    service:
      frigate:
        controller: frigate
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: 5000
            primary: true
          go2rtc:
            port: 1984
          rtsp:
            port: 8554
          webrtc-tcp:
            port: 8555
            protocol: TCP
          webrtc-udp:
            port: 8555
            protocol: UDP
    route:
      frigate:
        hostnames:
          - ${HOSTNAME}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: frigate
                port: http
    persistence:
      config:
        existingClaim: ${PVC_CLAIM}
      config-file:
        type: configMap
        name: frigate-config
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      media:
        existingClaim: frigate-media
        globalMounts:
          - path: /media/frigate
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
      tmpfs:
        type: emptyDir
        advancedMounts:
          frigate:
            app:
              - path: /tmp
                subPath: tmp
