---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name crd-schema-publisher
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        CLOUDFLARE_API_TOKEN: "{{ .GITHUB_PAGES }}"
        CLOUDFLARE_ACCOUNT_ID: "{{ .ACCOUNT_ID }}"
  dataFrom:
    - extract:
        key: cloudflare
