---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:1.2.4@sha256:cd40bdda9615bc57bddfa8791877608b1b48b5dab3bef85d98a3bf6f162a50c8
    container_name: meshcentral
    restart: unless-stopped
    networks:
      apps:
    environment:
      NODE_ENV: production
      TZ: Europe/Warsaw
    expose:
      - ${APP_PORT}
    volumes:
      - ./config/meshcentral.json:/opt/meshcentral/meshcentral-data/config.json
      - ${DATA_PATH}/data:/opt/meshcentral/meshcentral-data
      - ${DATA_PATH}/files:/opt/meshcentral/meshcentral-files
      - ${DATA_PATH}/backups:/opt/meshcentral/meshcentral-backups
    labels:
      traefik.enable: "true"
      traefik.http.services.meshcentral.loadbalancer.server.port: ${APP_PORT}
      traefik.http.routers.meshcentral.entrypoints: https
      traefik.http.routers.meshcentral.rule: Host(`${HOST}`)
      traefik.http.routers.meshcentral.tls: true
      traefik.http.routers.meshcentral.service: meshcentral
      dexd.enabled: "true"

networks:
  apps:
    external: true
