---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  scrutiny:
    image: ghcr.io/starosdev/scrutiny:1.66.0-omnibus@sha256:c3e4e42ae4c2a08bdbb48d24cc5ac19d0f2237b8e6e7ad3c72ff601795a6f1eb
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    restart: unless-stopped
    networks:
      apps:
    environment:
      TZ: Europe/Warsaw
      COLLECTOR_CRON_SCHEDULE: "0 * * * *"
      SCRUTINY_NOTIFY_URLS: "pushover://shoutrrr:${PUSHOVER_USER_KEY}@${PUSHOVER_SCRUTINY_KEY}/"
    expose:
      - ${APP_PORT}
    volumes:
      - /run/udev:/run/udev:ro
      - ${DATA_PATH}/config:/opt/scrutiny/config
      - ${DATA_PATH}/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/nvme0"
      - "/dev/nvme1"
      - "/dev/nvme2"
    labels:
      traefik.enable: "true"
      traefik.http.services.scrutiny.loadbalancer.server.port: ${APP_PORT}
      traefik.http.routers.scrutiny.entrypoints: https
      traefik.http.routers.scrutiny.rule: Host(`${HOST}`)
      traefik.http.routers.scrutiny.tls: true
      traefik.http.routers.scrutiny.service: scrutiny
      dexd.enabled: "true"

networks:
  apps:
    external: true
