---
mqtt:
  enabled: false

auth:
  enabled: true

tls:
  enabled: false

database:
  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  enabled: true
  fps: 5

record:
  enabled: true

snapshots:
  enabled: true

cameras:
  kids:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_KIDS_RTSP_USER}:{FRIGATE_KIDS_RTSP_PASSWORD}@camera-kids.ishioni.casa/live0
          roles:
            - detect
            - record
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_BEDROOM_RTSP_USER}:{FRIGATE_BEDROOM_RTSP_PASSWORD}@camera-bedroom.ishioni.casa/live0
          roles:
            - detect
            - record
