---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name changedetection
spec:
  refreshPolicy: CreatedOnce
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        TOKEN: "{{ .TOKEN }}"
        PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/?token={{ .TOKEN }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "TOKEN"
---
# yaml-language-server: $schema=https://crd.movishell.pl/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password32
spec:
  length: 32
  allowRepeat: true
  noUpper: false
  symbols: 0
