---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 30m
  values:
    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          folder: Storage
          matchLabels:
            grafana.internal/instance: grafana
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
