{
 "title": "UPS statistics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values(network_ups_tools_device_info, ups)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$ups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "ups",
   "targets": [
    {}
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{mfr}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Run Time Left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Line Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}"
    }
   ]
  }
 ]
}