---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: speedtest-exporter
  interval: 30m
  values:
    fullnameOverride: speedtest-exporter
    config:
      cacheFor: 1m
    monitoring:
      serviceMonitor:
        enabled: true
        interval: 5m
        scrapeTimeout: 120s
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          folder: Networking
          matchLabels:
            grafana.internal/instance: grafana
