---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: eep-test
  labels:
    app.kubernetes.io/name: eep-test
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: eep-test
  wasm:
    - name: eep
      rootID: eep
      code:
        type: Image
        image:
          url: oci://ghcr.io/ishioni/eep@sha256:716af7da00c1f28d64ed43f6b2dad29968efd7e781d620356f8117be8953a10e
          sha256: 716af7da00c1f28d64ed43f6b2dad29968efd7e781d620356f8117be8953a10e
      config:
        theme: ghost
        showDetails: true
        locale: auto
      failOpen: false
