---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: eep-test
  labels:
    app.kubernetes.io/name: eep-test
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: eep-test
  wasm:
    - name: eep
      rootID: eep
      code:
        type: Image
        image:
          url: oci://ghcr.io/ishioni/eep:sha256-7cbc6649435c0307cca06b4971fa2aa65f3346173ae0ce18bf39fb2903982b70
      config:
        theme: ghost
        showDetails: true
        locale: auto
      failOpen: false
