---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tofu-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: tofu-op-secret
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        OP_CONNECT_HOST: http://onepassword.security.svc.cluster.local:8080
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
  dataFrom:
    - extract:
        key: op-connect
---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tofu-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: tofu-backend-secret
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        access_key: "{{ .S3_ACCESS_KEY }}"
        secret_key: "{{ .S3_SECRET_KEY }}"

  dataFrom:
    - extract:
        key: tofu-controller
---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tofu-branch-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: tofu-backend-secret
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        token: "{{ .GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: tofu-controller
