---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserverentry_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServerEntry
metadata:
  name: homeassistant
spec:
  groupRef:
    name: mcp-tools
  remoteUrl: https://homeassistant.movishell.pl/api/webhook/mcp_383d1f2431b4ac760ee1134800fd561a
  transport: streamable-http
  externalAuthConfigRef:
    name: homeassistant
