---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: hass
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:7.3.0
  transport: streamable-http
  groupRef:
    name: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: http://haos.${PRIVATE_DOMAIN}:8123
  secrets:
    - name: haos-mcp-secret
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
