---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        ## OIDC
        HOMEPAGE_AUTH_SECRET: "{{ .homepage_AUTH_SECRET }}"
        HOMEPAGE_OIDC_AUTO_LOGIN: "true"
        HOMEPAGE_OIDC_ISSUER: "https://auth.movishell.pl/application/o/homepage/"
        HOMEPAGE_OIDC_CLIENT_ID: "{{ .homepage_OIDC_CLIENT_ID }}"
        HOMEPAGE_OIDC_CLIENT_SECRET: "{{ .homepage_OIDC_CLIENT_SECRET }}"
        HOMEPAGE_OIDC_SCOPE: "openid email profile"
        HOMEPAGE_OIDC_NAME: "Movishell"
        ## Infrastructure
        HOMEPAGE_VAR_UNIFI_TOKEN: "{{ .unifi_HOMEPAGE_KEY }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .homeassistant_HASS_TOKEN }}"
        HOMEPAGE_VAR_TRUENAS_TOKEN: "{{ .ix_csi_LEO_API_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .bazarr_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .prowlarr_PROWLARR__API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_RADARR__API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_SONARR__API_KEY }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .lidarr_LIDARR__API_KEY }}"
        HOMEPAGE_VAR_NAVIDROME_USER: "{{ .navidrome_username }}"
        HOMEPAGE_VAR_NAVIDROME_SALT: "{{ .navidrome_NAVIDROME_SALT }}"
        HOMEPAGE_VAR_NAVIDROME_TOKEN: "{{ .navidrome_NAVIDROME_TOKEN }}"
        ## Security
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .authentik_TERRAFORM_TOKEN }}"
        ## Selfhosted
        HOMEPAGE_VAR_IMMICH_TOKEN: "{{ .immich_HOMEPAGE_API_TOKEN }}"
        HOMEPAGE_VAR_SLSKD_API_KEY: "{{ .slskd_SLSKD_API_KEY }}"
  dataFrom:
    ## OIDC
    - extract:
        key: homepage
      rewrite:
        - regexp: { source: "(.*)", target: "homepage_$1" }
    ## Non Cluster
    - extract:
        key: unifi
      rewrite:
        - regexp: { source: "(.*)", target: "unifi_$1" }
    - extract:
        key: homeassistant
      rewrite:
        - regexp: { source: "(.*)", target: "homeassistant_$1" }
    - extract:
        key: ix-csi
      rewrite:
        - regexp: { source: "(.*)", target: "ix_csi_$1" }
    ## Downloads
    - extract:
        key: bazarr
      rewrite:
        - regexp: { source: "(.*)", target: "bazarr_$1" }
    - extract:
        key: prowlarr
      rewrite:
        - regexp: { source: "(.*)", target: "prowlarr_$1" }
    - extract:
        key: radarr
      rewrite:
        - regexp: { source: "(.*)", target: "radarr_$1" }
    - extract:
        key: sonarr
      rewrite:
        - regexp: { source: "(.*)", target: "sonarr_$1" }
    - extract:
        key: lidarr
      rewrite:
        - regexp: { source: "(.*)", target: "lidarr_$1" }
    - extract:
        key: slskd
      rewrite:
        - regexp: { source: "(.*)", target: "slskd_$1" }
    ## Security
    - extract:
        key: authentik
      rewrite:
        - regexp: { source: "(.*)", target: "authentik_$1" }
    - extract:
        key: immich
      rewrite:
        - regexp: { source: "(.*)", target: "immich_$1" }
    - extract:
        key: navidrome
      rewrite:
        - regexp: { source: "(.*)", target: "navidrome_$1" }
