---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
spec:
  chartRef:
    kind: OCIRepository
    name: slskd
  interval: 30m
  values:
    controllers:
      slskd:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret slskd-secret
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.24.5@sha256:17ef977563be206f3b5932080b1e23883b2cb39dc9010640f6f39b4eaec887e3
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: ${CONFIG_TIMEZONE}
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_NO_VERSION_CHECK: true
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50429
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 1000Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 5000
        fsGroup: 5000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
      soulseek:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.84.2.4
        labels:
          io.cilium/ippool: public
        externalTrafficPolicy: Local
        ports:
          soulseek-tcp:
            port: *soulseekPort
            protocol: TCP
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Slskd
          gethomepage.dev/icon: slskd.svg
        hostnames: ["${HOSTNAME}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    configMaps:
      config:
        data:
          slskd.yml: |-
            directories:
              downloads: /media/Downloads/soulseek/complete
              incomplete: /media/Downloads/soulseek/incomplete
            shares:
              directories:
                - /media/Music
              filters:
                - \.ini$
                - Thumbs.db$
                - \.DS_Store$
    persistence:
      config:
        existingClaim: ${PVC_CLAIM}
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
      media:
        existingClaim: downloads-pvc
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
