---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name go2rtc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        RTSP_PATHS_BEDCAM_SOURCE: |-
          rtsp://{{ .BEDCAM_USER }}:{{ .BEDCAM_PASSWORD }}@bedcam.ishioni.casa/Preview_01_main
        RTSP_PATHS_KIDSCAM_SOURCE: |-
          rtsp://{{ .KIDSCAM_USER }}:{{ .KIDSCAM_PASSWORD }}@kidscam.ishioni.casa/Preview_01_main
  dataFrom:
    - extract:
        key: reolink
