---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  chartRef:
    kind: OCIRepository
    name: kyverno
  maxHistory: 3
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    crds:
      install: true
      migration:
        image:
          registry: ghcr.io
    admissionController:
      initContainer:
        image:
          registry: ghcr.io
      container:
        image:
          registry: ghcr.io
      replicas: 3
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: kyverno
              app.kubernetes.io/component: kyverno
    backgroundController:
      image:
        registry: ghcr.io
      serviceMonitor:
        enabled: true
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
    cleanupController:
      image:
        registry: ghcr.io
      serviceMonitor:
        enabled: true
    reportsController:
      image:
        registry: ghcr.io
      serviceMonitor:
        enabled: true
    grafana:
      enabled: true
      annotations:
        grafana_folder: Kubernetes
