{
 "title": "Connect Box",
 "description": "Dashboard for Compal CH7465LG cable modems (marketed as \"Connect Box\" by several carriers)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(connectbox_device_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device overview for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Provisioning Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_provisioning_status{instance=~\"$instance\"} == 1",
     "legendFormat": "{{ connectbox_provisioning_status }}"
    }
   ]
  },
  {
   "title": "ISP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_device_info{instance=~\"$instance\"}",
     "legendFormat": "{{ operator_id }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(connectbox_uptime_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Upstream Timeouts in Last Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(connectbox_upstream_timeouts_total{instance=~\"$instance\"}[60m]))"
    }
   ]
  },
  {
   "title": "Minimum Downstream RxMER",
   "type": "stat",
   "description": "Assuming 256QAM modulation, [30dB is the minimum, 33dB or higher is recommended](https://pickmymodem.com/signal-levels-docsis-3-03-1-cable-modem/).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(connectbox_downstream_rxmer_db{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Tuner Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(instance) (connectbox_tuner_temperature_celsius{instance=~\"$instance\"})",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Cable Modem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_device_info{instance=~\"$instance\"}",
     "legendFormat": "{{ cable_modem_status }}"
    }
   ]
  },
  {
   "title": "Connection Standard",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_device_info{instance=~\"$instance\"}",
     "legendFormat": "{{ docsis_mode }}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_device_info{instance=~\"$instance\"}",
     "legendFormat": "{{ hardware_version }}"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "connectbox_device_info{instance=~\"$instance\"}",
     "legendFormat": "{{ firmware_version }}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(connectbox_ethernet_client_speed_mbit{instance=~\"$instance\"})",
     "legendFormat": "LAN"
    },
    {
     "expr": "count(connectbox_wifi_client_speed_mbit{instance=~\"$instance\"})",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  { "title": "Downstream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Downstream RxMER",
   "type": "timeseries",
   "description": "Receive modulation error ratio (RxMER). [The higher the MER, the cleaner the received signal.](https://www.intraway.com/blog/monitoring-DOCSIS-3.1)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by(instance,channel_id) (connectbox_downstream_rxmer_db{instance=~\"$instance\"})",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Corrected Codewords per Second",
   "type": "timeseries",
   "description": "Based on data from the past 5 minutes, what percentage of codewords was successfully corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(channel_id, instance) (rate(connectbox_downstream_codewords_corrected_total{instance=~\"$instance\"}[5m])) / (sum by(channel_id, instance) (rate(connectbox_downstream_codewords_unerrored_total{instance=~\"$instance\"}[5m])) + sum by(channel_id, instance) (rate(connectbox_downstream_codewords_corrected_total{instance=~\"$instance\"}[5m])) + sum by(channel_id, instance) (rate(connectbox_downstream_codewords_uncorrectable_total{instance=~\"$instance\"}[5m])))",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Uncorrectable Codewords per Second",
   "type": "timeseries",
   "description": "Based on data from the past 5 minutes, what percentage of codewords could not be corrected per second?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(channel_id, instance) (rate(connectbox_downstream_codewords_uncorrectable_total{instance=~\"$instance\"}[5m])) / (sum by(channel_id, instance) (rate(connectbox_downstream_codewords_unerrored_total{instance=~\"$instance\"}[5m])) + sum by(channel_id, instance) (rate(connectbox_downstream_codewords_corrected_total{instance=~\"$instance\"}[5m])) + sum by(channel_id, instance) (rate(connectbox_downstream_codewords_uncorrectable_total{instance=~\"$instance\"}[5m])))",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Downstream Channel Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by(channel_id, instance) (connectbox_downstream_frequency_hz{instance=~\"$instance\"})",
     "legendFormat": "Ch. {{ channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream Channel Power Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "avg by(instance,channel_id) (connectbox_downstream_power_level_dbmv{instance=~\"$instance\"})",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  { "title": "Upstream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Number of Timeouts per 15min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(connectbox_upstream_timeouts_total{instance=~\"$instance\"}[15m])) by (timeout_type)",
     "legendFormat": "{{ timeout_type }} timeout"
    }
   ]
  },
  {
   "title": "Upstream Channel Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by(channel_id, instance) (connectbox_upstream_frequency_hz{instance=~\"$instance\"})",
     "legendFormat": "Ch. {{ channel_id}}"
    }
   ]
  },
  {
   "title": "Upstream Channel Power Level",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "avg by(instance,channel_id) (connectbox_upstream_power_level_dbmv{instance=~\"$instance\"})",
     "legendFormat": "Ch. {{ channel_id }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Temperature",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max by(instance) (connectbox_tuner_temperature_celsius{instance=~\"$instance\"})",
       "legendFormat": "Tuner"
      },
      {
       "expr": "max by(instance) (connectbox_temperature_celsius{instance=~\"$instance\"})",
       "legendFormat": "Device"
      }
     ]
    }
   ]
  },
  {
   "title": "LAN Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Client Connection Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by (hostname, ipv4_address) (connectbox_ethernet_client_speed_mbit{instance=~\"$instance\"})",
       "legendFormat": "{{ hostname }} ({{ ipv4_address }})"
      }
     ]
    },
    {
     "title": "Wi-Fi Client Connection Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(hostname, ipv4_address) (connectbox_wifi_client_speed_mbit{instance=~\"$instance\"})",
       "legendFormat": "{{ hostname }} ({{ ipv4_address }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectbox Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true
  },
  {
   "title": "Connectbox Exporter Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance,extractor) (connectbox_scrape_duration_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{ extractor }}"
    },
    {
     "expr": "sum by(instance) (connectbox_scrape_duration_seconds{instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Connectbox Exporter Scrape Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, extractor) (connectbox_up{instance=~\"$instance\"})",
     "legendFormat": "{{ extractor }}"
    }
   ]
  }
 ]
}