---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bookboss-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # App
        BOOKBOSS__DATABASE__DATABASE_URL: postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.database.svc.cluster.local:5432/bookboss
        BOOKBOSS__OIDC__DISCOVERY_URL:
        BOOKBOSS__OIDC__CLIENT_ID:
        BOOKBOSS__OIDC__CLIENT_SECRET:
        BOOKBOSS__OIDC__BUTTON_LABEL:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .ENCRYPTION_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: bookboss
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: bookboss
    - extract:
        key: cloudnative-pg
