---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookboss
spec:
  chartRef:
    kind: OCIRepository
    name: bookboss
  interval: 30m
  values:
    controllers:
      bookboss:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret bookboss-secret
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secret
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 5000
            fsGroup: 5000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/szinn/bookboss
              tag: v0.8.30@sha256:073a9e71fb731e624fe5d8f415df457685b5b3c66a613f610c3188a6c689a3db
            env:
              BOOKBOSS__FRONTEND__BASE_URL: "https://${HOSTNAME}"
              BOOKBOSS__LIBRARY__LIBRARY_PATH: "/media/Books"
              BOOKBOSS__IMPORT__BOOKDROP_PATH: "/media/Downloads/books"
              TZ: ${CONFIG_TIMEZONE}
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    service:
      app:
        controller: bookboss
        ports:
          http:
            port: *port
            primary: true
          grpc:
            port: 8081
            targetPort: 8081
            appProtocol: grpc
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            url: "https://${HOSTNAME}/healthz"
            conditions: ["[STATUS] == 200"]
        hostnames: ["${HOSTNAME}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
    persistence:
      tmp:
        type: emptyDir
      media:
        existingClaim: downloads-pvc
        globalMounts:
          - path: /media
